# Generated by Django 4.1.13 on 2024-03-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anaweb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ekibimiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=100)),
                ("image", models.ImageField(upload_to="media/Ekibimiz/")),
            ],
        ),
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(upload_to="media/slider/"),
        ),
    ]
