# Generated by Django 4.1.13 on 2024-03-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anaweb", "0002_ekibimiz_alter_slider_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Galeri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/Galeri")),
            ],
        ),
    ]
